spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/testmwamwa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
      username: root
      password: Hello@1122

  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

  thymeleaf:
    cache: 'false'

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: 'false'
    show-sql: 'true'
    open-in-view: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        default_batch_fetch_size: '100'

  mail:
    host: smtp.gmail.com
    port: 587
    username: mwamwayabab@gmail.com
    password: rwnmcktwuuvxuers
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분